Update surf-browser-binary-main.yml

diff --git a/.github/workflows/surf-browser-binary-main.yml b/.github/workflows/surf-browser-binary-main.yml
--- a/.github/workflows/surf-browser-binary-main.yml
+++ b/.github/workflows/surf-browser-binary-main.yml
@@ -58,8 +58,9 @@ jobs:
 
       - name: Clone WebKitGTK
         run: |
-          git clone --depth 1 --branch main https://github.com/WebKit/WebKit.git webkitgtk
+          git clone --depth 1 https://github.com/WebKit/WebKit.git webkitgtk
           cd webkitgtk || { echo "Failed to cd into webkitgtk"; exit 1; }
+          git checkout 8284df1e1c0c80b17c26849451764d719ba8e424 || { echo "Failed to checkout commit"; exit 1; }
 
       - name: Build and Install WebKitGTK
         run: |
@@ -77,6 +78,7 @@ jobs:
             -DUSE_WPE_RENDERER=OFF \
             -DUSE_LIBNOTIFY=OFF \
             -DENABLE_JOURNALD_LOG=OFF \
+            -DUSE_GTK4=OFF \
             -GNinja ..
           ninja || { echo "WebKitGTK build failed"; exit 1; }
           ninja install || { echo "WebKitGTK install failed"; exit 1; }
